- name: Build and Deploy Petstore
  hosts: local
  become: yes
  tasks:
   - name: Build and Push Docker image
     community.docker.docker_image:
       name: "akhilKuchipudi26111997/petstore"
       repository: "docker.io/akhilKuchipudi26111997/petstore"
       tag: latest
       source: build
       build:
         path: /var/lib/jenkins/workspace/petstore
       push: true

    - name: Run Petstore container
      community.docker.docker_container:
        name: pet1
        image: "akhilKuchipudi26111997/petstore:latest"
        state: started
        restart_policy: always
        published_ports:
          - "8090:8080"
